---
- hosts: all
  become: true
  tasks:
    - name: Assert that OS-family supported
      ansible.builtin.assert:
        that: "ansible_os_family == 'Debian'"
        fail_msg: "OS family incorrect {{ ansible_os_family }} != Debian"

    - name: Adding administrative user
      ansible.builtin.user:
        name: user
        password: "{{ 'qweASD!@#' | string | password_hash('sha512', 'secretsaltpangol') }}"
        groups: sudo
        shell: /bin/bash
        create_home: true
        append: true

    - name: Allow the user to sudo
      community.general.sudoers:
        name: user
        state: present
        user: user
        nopassword: true
        commands: ALL

- hosts: localhost
  gather_facts: False
  tasks:
    - name: Compress string via jinja2 template
      ansible.builtin.template:
        src: ./templates/task3.j2
        dest: output.txt
        mode: '0644'

    - name: Read contents of a file and remove spaces
      ansible.builtin.set_fact:
        content: "{{ lookup('file', 'output.txt') | replace(' ', '') }}"
    
    - name: Display the content without sp
      ansible.builtin.debug:
        msg: "{{ content }}"
